[book]
title = "Minipas"
authors = ["Jorge Brunal PÃ©rez"]
description = "Minipas programming language."
language = "es"

[rust]
edition = "2024"

[build]
build-dir = "book"
create-missing = true # false

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
# definition-lists = true
# admonitions = true
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/HomeInside/minipas"
git-repository-icon = "fab-github"
# edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/docs/guide/{path}"
site-url = "/book/"
# sidebar-header-nav = true
#
# additional-css = ["css/styles.css"]  # Ruta a tu archivo CSS personalizado
# additional-js = ["js/highlight.min.js", "js/highlightjs-line-numbers.min.js", "js/custom.js"]
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]

# [output.html.print]
# enable = true    # include support for printable output
# page-break = true # insert page-break after each chapter

[output.html.search]
limit-results = 20       # maximum number of search results
teaser-word-count = 20   # number of words used for a search result teaser

[output.html.playground]
runnable = false          # displays a run button for rust code
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
